# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scientific Array Data Exchange
email: aradi@uni-bremen.de
description: > # this means to ignore newlines until "baseurl:"
  Protocol for exchanging structured array data between applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://saydx.github.io" # the base hostname & protocol for your site
#twitter_username: saydx
github_username:  saydx

# Build settings
sass:
    sass_dir: _sass
include: ['_pages']
markdown: kramdown
kramdown:
    input: GFM


#  using various different transport layers, such as binary API, file I/O, socket communications and MPI-messaging.
